#!/bin/bash

##
# Switch
# =========
# @author Philip Blyth
#
#
# Installation:
# -------------
# * On dev instance, save to:
#     ~/vm_home_devuser/scripts/
#
# * Make sure is executable:
#     chmod +x ~/vm_home_devuser/scripts/switch
#
# * Symlink to 'bin':
#     ln ~/vm_home_devuser/scripts/switch /usr/local/bin/switch
#
#
# Hierarchy:
# ----------
# This script expects the following hierarchy:
#
# - web-cpg
#   - active
#     - webroot
#     - ...
#   - branches
#     - RFC-xxxx
#       - webroot
#       - ...
#     - WCPG-xxxx
#       - webroot
#       - ...
#
#
# Usage:
# ------
# * !!! will only run in 'web-[...]' folders !!!
# * run:
#     switch help
#     switch <branch>
#


if [[ $# -gt 0 ]]; then

	if [[ $1 == "help" ]]; then

		# output help
		cat <<-'TOKEN'
			----------
			Moves the 'active' folder to 'branches', renaming it to active's branch name,
			and promotes a branch folder from 'branches' to become the new 'active'.

			Usage: switch <branch>
			Parameters:
			    <branch>: name of SVN branch to swap to.
			----------
		TOKEN

	else

		# get current SVN branch name
		current=`cd active && svn info | grep URL --max-count=1 --line-buffered | sed s/"\(^.*\/\)\([^/]*\)$"/"\2"/`;
		# get new SVN branch name from 1st argument
		new=$1;

		# move current
		mv active branches/$current;

		# move new
		mv branches/$new active;

	fi
else
	echo "Missing <branch> argument! (use '$0 help' for usage)";
fi
